appname: "erulb"
entrypoints:
    beta-host:
        cmd: "nginx -p /erulb/server -c /erulb/conf/beta.conf"
        ports:
            - "80/tcp"
        network_mode: "host"
version: "raw_version_for_dns"
build: ""
